import News1 from "../assets/images/news-1.jpg";
import News2 from "../assets/images/news-2.jpg";
import News3 from "../assets/images/news-3.jpg";
import News4 from "../assets/images/news-4.jpg";

export const news = [
  {
    id: 1,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News1,
    theme: "Saúde",
    title: "Inauguração de Novo Centro de Saúde Municipal",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 2,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News2,
    theme: "Mobilidade urbana",
    title: "Prefeito Anuncia Novas Medidas de Segurança no Trânsito",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 3,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News3,
    theme: "Edução e emprego",
    title: "Prefeitura Lança Programa de Capacitação Profissional",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 4,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News4,
    theme: "Infraestrutura e urbanismo",
    title: "Obras de Revitalização da Praça Central Entram na Fase Final",
    description:
      "Espaço ganhará novas áreas de lazer e acessibilidade para todos os moradores.",
  },
  {
    id: 5,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News1,
    theme: "Saúde",
    title: "Inauguração de Novo Centro de Saúde Municipal",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 6,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News2,
    theme: "Mobilidade urbana",
    title: "Prefeito Anuncia Novas Medidas de Segurança no Trânsito",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 7,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News3,
    theme: "Edução e emprego",
    title: "Prefeitura Lança Programa de Capacitação Profissional",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 8,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News4,
    theme: "Infraestrutura e urbanismo",
    title: "Obras de Revitalização da Praça Central Entram na Fase Final",
    description:
      "Espaço ganhará novas áreas de lazer e acessibilidade para todos os moradores.",
  },
  {
    id: 9,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News1,
    theme: "Saúde 9",
    title: "Inauguração de Novo Centro de Saúde Municipal",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 10,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News2,
    theme: "Mobilidade urbana 10",
    title: "Prefeito Anuncia Novas Medidas de Segurança no Trânsito",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 11,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News3,
    theme: "Edução e emprego",
    title: "Prefeitura Lança Programa de Capacitação Profissional",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 12,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News4,
    theme: "Infraestrutura e urbanismo",
    title: "Obras de Revitalização da Praça Central Entram na Fase Final",
    description:
      "Espaço ganhará novas áreas de lazer e acessibilidade para todos os moradores.",
  },
  {
    id: 13,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News1,
    theme: "Saúde",
    title: "Inauguração de Novo Centro de Saúde Municipal",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 14,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News2,
    theme: "Mobilidade urbana 14",
    title: "Prefeito Anuncia Novas Medidas de Segurança no Trânsito",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 15,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News3,
    theme: "Edução e emprego 15",
    title: "Prefeitura Lança Programa de Capacitação Profissional",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 16,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News4,
    theme: "Infraestrutura e urbanismo 16",
    title: "Obras de Revitalização da Praça Central Entram na Fase Final",
    description:
      "Espaço ganhará novas áreas de lazer e acessibilidade para todos os moradores.",
  },
  {
    id: 17,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News1,
    theme: "Saúde 17",
    title: "Inauguração de Novo Centro de Saúde Municipal",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 18,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News2,
    theme: "Mobilidade urbana 18",
    title: "Prefeito Anuncia Novas Medidas de Segurança no Trânsito",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 19,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News3,
    theme: "Edução e emprego 19",
    title: "Prefeitura Lança Programa de Capacitação Profissional",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 20,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News4,
    theme: "Infraestrutura e urbanismo20",
    title: "Obras de Revitalização da Praça Central Entram na Fase Final",
    description:
      "Espaço ganhará novas áreas de lazer e acessibilidade para todos os moradores.",
  },
  {
    id: 21,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News1,
    theme: "Saúde 21",
    title: "Inauguração de Novo Centro de Saúde Municipal",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 22,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News2,
    theme: "Mobilidade urbana 22",
    title: "Prefeito Anuncia Novas Medidas de Segurança no Trânsito",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 23,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News3,
    theme: "Edução e emprego 23",
    title: "Prefeitura Lança Programa de Capacitação Profissional",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 24,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News4,
    theme: "Infraestrutura e urbanismo 24",
    title: "Obras de Revitalização da Praça Central Entram na Fase Final",
    description:
      "Espaço ganhará novas áreas de lazer e acessibilidade para todos os moradores.",
  },
  {
    id: 25,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News2,
    theme: "Mobilidade urbana 22",
    title: "Prefeito Anuncia Novas Medidas de Segurança no Trânsito",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 26,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News3,
    theme: "Edução e emprego 23",
    title: "Prefeitura Lança Programa de Capacitação Profissional",
    description:
      "Unidade moderna amplia atendimento e garante mais qualidade de vida à população.",
  },
  {
    id: 27,
    date: "08/10/2024",
    time: "11:04",
    author: "Gabriele Letícia Ledur",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet turpis rutrum, rutrum nunc imperdiet, ornare diam. In ut elementum felis. Aenean vel lacinia est. Fusce at tempor ante. Duis sed ligula a felis gravida hendrerit nec feugiat nibh. Cras dapibus quam eget velit sollicitudin luctus. Phasellus eleifend orci ut eros posuere, sit amet facilisis leo convallis. Sed ac tincidunt elit. Sed vel mauris nunc. Maecenas accumsan purus in leo rutrum, sit amet euismod risus ultricies. Integer eget hendrerit est, quis imperdiet elit. Vestibulum suscipit elit ante, feugiat facilisis elit maximus et. <br/> <br/>Suspendisse volutpat blandit dolor, quis vulputate justo. Pellentesque dapibus magna eget metus consequat fermentum. Pellentesque ornare in est eu ullamcorper. Suspendisse erat lacus, porta id lobortis sed, fermentum nec ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas cursus ipsum risus, sed consectetur libero egestas non. Integer sollicitudin nisi ac sem tempor, ut lacinia neque venenatis. Aenean sit amet mi at tellus pretium pharetra. Ut ultrices, nibh ut tincidunt volutpat, elit arcu dictum risus, quis cursus ante turpis nec turpis. Maecenas vitae urna at eros cursus tempor. Phasellus quis nibh tortor. <br/> <br/> Fusce id orci sed elit efficitur fringilla vel facilisis ante. Integer est risus, bibendum quis leo non, porta blandit quam. Proin eleifend est purus, ut facilisis eros egestas non. Phasellus ornare diam vulputate maximus aliquam. Nam justo nibh, porttitor ut efficitur vel, fermentum sit amet ante. Mauris pharetra lectus nec eros finibus dapibus. Nunc eu eros eu nunc lacinia tempus.",
    image: News4,
    theme: "Infraestrutura e urbanismo 24",
    title: "Obras de Revitalização da Praça Central Entram na Fase Final",
    description:
      "Espaço ganhará novas áreas de lazer e acessibilidade para todos os moradores.",
  },
];
